version: '3.4'

services:
  postgresql_database:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=currency
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - postgresql-database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - '5050:80'
    restart: always
    volumes:
      - pgadmin:/var/lib/postgresql/pgadmin/
    networks:
      - postgresql-database

networks:
  postgresql-database:
    driver: bridge

volumes:
  database-data:
  pgadmin: