server:
  port: 8081

spring:
  application:
    name: currency-service
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/currency
    password: 'admin1234'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create-drop
      show-sql: true

bank:
  api:
    uri: https://api.apilayer.com/exchangerates_data/latest?symbols=GBP%2CJPY%2CEUR&base=USD